// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type ManuscriptInfo struct {
	Id     int64  `json:"id"`
	Status string `json:"status"`
	Title  string `json:"title"`
}

type PageRequest struct {
	PageNo   int64  `form:"pageNo,optional"`
	PageSize int64  `form:"pageSize,optional"`
	Keyword  string `form:"keyword,optional"`
}

type PageResponse struct {
	Total    int64 `json:"total"`
	PageNo   int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
}
