# docker-compose up -d
# docker-compose build --no-cache && docker-compose up -d
# docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d

services:
  mesas:
    build:
      context: .
      dockerfile: ./app/mesas/cmd/api/Dockerfile
      args:
        GO_FILE: ./app/mesas/cmd/api/mesas.go
        GO_ETC: ./app/mesas/cmd/api/etc
    ports:
      - 1001
    networks:
      - api-backend
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai

  oae:
    build:
      context: .
      dockerfile: ./app/oae/cmd/api/Dockerfile
      args:
        GO_FILE: ./app/oae/cmd/api/oae.go
        GO_ETC: ./app/oae/cmd/api/etc
    ports:
      - 1002
    networks:
      - api-backend
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai

  # 后端代理
  nginx-api:
    image: nginx:latest
    container_name: nginx-api
    volumes:
      - ./deploy/nginx/conf.d/api.conf:/etc/nginx/conf.d/api.conf
    ports:
      - "1010:80"
    networks:
      - api-backend

networks:
  api-backend:
    driver: bridge