# sudo docker login --username=木子镓 crpi-wnfek3pn2k4kqc1p.cn-chengdu.personal.cr.aliyuncs.com
# docker-compose up -d
# docker-compose build --no-cache && docker-compose up -d

services:
  mesas:
    build:
      context: .
      dockerfile: ./app/mesas/cmd/api/Dockerfile
      args:
        GO_FILE: ./app/mesas/cmd/api/mesas.go
        GO_ETC: ./app/mesas/cmd/api/etc
    container_name: "mesas"
    ports:
      - "1001:1001"
    networks:
      - api-backend
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
  oae:
    build:
      context: .
      dockerfile: ./app/oae/cmd/api/Dockerfile
      args:
        GO_FILE: ./app/oae/cmd/api/oae.go
        GO_ETC: ./app/oae/cmd/api/etc
    container_name: "oae"
    ports:
      - "1002:1002"
    networks:
      - api-backend
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai

  # 后端代理
  nginx-api:
    image: nginx:latest
    container_name: nginx-api
    volumes:
      - ./deploy/nginx/conf.d/api.conf:/etc/nginx/conf.d/api.conf
    ports:
      - "1010:80"
    networks:
      - api-backend

networks:
  api-backend:
    driver: bridge