// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	manuscript "go-microservice/app/oae/cmd/api/internal/handler/manuscript"
	"go-microservice/app/oae/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取稿件信息
				Method:  http.MethodGet,
				Path:    "/manuscript/:id",
				Handler: manuscript.GetManuscriptHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
